### PR TITLE
Specify type of send from templateType

### LINKED ISSUE #303: Trouble with syntax for bw send create using send.file template
Sorry if this is the wrong place for this.

```shell
$ bw --version
1.16.0
```

I'm trying to use `send.file` template in a script to create File Sends, but I'm failing somewhere. Here's the basic format I'm using:

#### bwtest.sh:
```shell
#!/usr/bin/env bash

function _bwsend() {
  [ -e "$1" ] || return
  bw send template send.file |
  jq --arg f "$1" '.name="foo" | .text="bar" | .notes="mynote" | .file.fileName=$f' |
  bw encode |
  bw send create --fullObject
}

_bwsend "$1"
```

```
$ bwtest.sh "some_file.zip"
Must specify text content to Send either with the --text option or in the encoded json
```

I've tried many different permutations of the command arguments but can't seem to find the magic incantation. Any tips?

### PR DESCRIPTION
**Pull request by MGibson1**
# Overview

Fixes #303.
Correctly specify the send type for different Send templates.

### CODE REVIEW

File: src/models/response/sendResponse.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ export class SendResponse implements BaseResponse {
         const req = new SendResponse();
         req.name = 'Send name';
         req.notes = 'Some notes about this send.';
-        req.type = SendType.Text;
+        req.type = sendType === SendType.Text ? SendType.Text : SendType.File;
```
Comment (cscharf) [inline src/models/response/sendResponse.ts:21]: As a matter of nits around defaults, I would feel more comfortable if this was a check against `if File then File, otherwise Text` vs. as it is here where it assumes file if not text... it's a tiny nuance but I think Text is our go-to default type of Send and the only type that doesn't require premium plans, etc. so better that one's implicit where file is left explicit IMHO.

Comment (MGibson1) [reply src/models/response/sendResponse.ts:21]: No I agree with you, I was just thinking about that as well, thanks for the feedback

**Review by cscharf — APPROVED** [review]
